---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE,
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# ETHIC Opioid Environment Program

This repository stores R scripts used to clean, join, and visualize data for the ETHIC opioid environment program. Raw data/output is not stored in here for confidentiality, but are included in the Google Drive/Box associated with this project.

| Input                         | Script                        | Output                        | Purpose                       |
|-------------------------------|-------------------------------|-------------------------------|-------------------------------|
| data/*                        | R/01_*                        | data-output/01_*              | Clean original data and get each into 3-column format with `name`, `category_service`, and `geometry` |
| data-output/01_*              | R/02_*                        | data-output/02_*              | Combine datasets together to get combined point dataset (needed for map overlays), create point maps for each resource (for jurisdictional plan) |
| data-output/02_*              | R/03_*                        | data-output/03_*              | **(unused)** Create various buffers on point dataset, count buffers per zip |
| data-output/01_*              | R/04_*                        | data-output/min-dists-to-zip-centroid.csv              | Calculate min distance from resources to zip centroids |
| data-output/min-dists-to-zip-centroid.csv              | R/05_*                        | data-output/sum_zscores.gpkg/.shp              | Convert centroid distances to summative z-scores |
| data/carto....              | R/99_*                        | data-output/carto...            | One-off cleaning/joining scripts for manipulating CARTO datasets for collaborators |

## Relevant Links

* [Google Drive](https://drive.google.com/drive/folders/1WOEZU8e56SiuENpqYbU1-Tf4HFa4aIeD): inlcudes raw data, cleaned data, and documentation
* [Trello](https://trello.com/b/r8b41gb0/ethic-opioid-environment-program): tasklist and status of project
* [ETHIC Access Google Sheet](https://docs.google.com/spreadsheets/d/1GEZZcFkQd-944-DKvqG6Wh_aJ60FG0Y9GuNS8EtFLY8/edit#gid=0): tracks access variables used in calculations