import Head from "next/head";
import styles from "../styles/About.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

const contributors = [
  {
    name:'Marynia Kolak',
    photo: 'marynia.jpg',
    link: 'https://github.com/Makosak'
  },
  {
    name:'Susan Paykin',
    photo: 'susan.jpg',
    link: 'https://github.com/spaykin'
  },
  {
    name:'Qinyun Lin',
    photo: 'qlin.jpg',
    link: 'https://github.com/linqinyu'
  },
  {
    name:'Dylan Halpern',
    photo: 'dylan.jpg',
    link: 'https://github.com/nofurtherinformation'
  }
]

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About :: OEPS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          media="print"
          onLoad="this.media='all'"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          />
        </noscript>
      </Head>
      <MainNav />
      <main className={styles.main}>
        <h1 className={styles.title}>About OEPS</h1>
        <Gutter em={3} />
        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>About</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
            The Opioid Environment Policy Scan (OEPS) is an open-source data platform providing access to data at 
            multiple spatial scales to help characterize the multi-dimensional risk environment impacting opioid use 
            in justice populations across the United States.
            </p>
            <p>
            The OEPS is led and maintained by the team at the <a href="https://voices.uchicago.edu/herop/">Healthy Regions and Policies Lab</a> (HEROP), 
            Center for Spatial Data Science at University of Chicago. It was developed for the <a href="https://heal.nih.gov/research/research-to-practice/jcoin">Justice Community Opioid Innovation Network (JCOIN)</a>, 
            an NIH HEAL Initiative, as part of the Methodology and Advanced Analytics Resource Center (MAARC). 
            Data and additional resources are also available to the JCOIN Network through the 
            <a href="https://jcoin.datacommons.io/login"> JCOIN Data Commons</a>.
            </p>
            <p>
            We developed the OEPS as a free, open-source platform to aggregate and share publicly-available data at the Census tract, zip code, county, and state levels. 
            Geographic boundary shapefiles are provided for ease of merging datasets (csv files) for exploration, spatial analysis, or visualization.
            <a href="/download"> Download</a> the entire data repository, or you can filter and download by theme or spatial scale. 
            All datasets are accompanied by <a href="/docs">metadata docs</a>, detailing their source data, year, and more. 
            Learn more about our methods and approaches, including the risk environment framework, in <a href="/methods">Methodology</a>.
            </p>
            <p>
            All data, metadata descriptions, and code is available on <a href="https://github.com/GeoDaCenter/opioid-policy-scan">GitHub</a>. 
            As an open source project, we encourage users to 
            <a href="https://docs.github.com/en/issues/organizing-your-work-with-project-boards/tracking-work-with-project-boards/adding-issues-and-pull-requests-to-a-project-board"> add an Issue </a> 
            on our GitHub for questions, bugs, or data requests, or <a href="https://docs.github.com/en/get-started/quickstart/fork-a-repo">fork the repo </a> 
            to access locally. 
            </p>
          </div>
        </div>
        <Gutter em={3} />
        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Team</h2> <a id="team"></a>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <div className={"row " + styles.contributorsContainer}>
              {contributors.map(entry => 
                <div className="col-xs-12 col-md-3 col-lg-3" key={entry.name}>
                  <img src={`images/team/${entry.photo}`} />
                  <h3><a href={entry.link}>{entry.name}</a></h3>
                  <h4>{entry.title}</h4>
                </div>)}
            </div>
            <p>
              Contributors include Moksha Menghaney and Angela Li, as well as Research Assistants (RAs) 
              Margot Bolanos Gamez, Alexa Jin, Ally Muszynski, and Rachel Vigil. 
            </p>
            <p>
              <b><a href="https://voices.uchicago.edu/herop/team/">Learn more</a></b> about the HEROP team.
            </p>
          </div>
        </div>
        <Gutter em={3} />
        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Contact</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p> 
            Submit an issue on <a href="https://github.com/GeoDaCenter/opioid-policy-scan">GitHub</a>, 
            or email <a href="mailto:spaykin@uchicago.edu">Susan Paykin</a> with any questions.
            </p>
          </div>
        </div>
        <Gutter em={3} />
        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Citation</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
            Marynia Kolak, Qinyun Lin, Susan Paykin, Moksha Menghaney, Angela Li. (2021, May 11). 
            GeoDaCenter/opioid-policy-scan: Opioid Environment Policy Scan Data Warehouse (Version v0.1-beta). Zenodo. 
            http://doi.org/10.5281/zenodo.4747876
            </p>
            <p>
            <i>This research was supported by the National Institute on Drug Abuse, National Institutes of Health, 
            through the NIH HEAL Initiative under award number UG3DA123456. 
            The contents of this publication are solely the responsibility of the authors and do not necessarily represent 
            the official views of the NIH, the Initiative, or the participating sites.</i>
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
