import Head from "next/head";
import styles from "../styles/About.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Code and Analysis Resources :: OEPS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          media="print"
          onLoad="this.media='all'"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          />
        </noscript>
      </Head>
      <MainNav />
      <main className={styles.main}>
        <h1 className={styles.title}>Code and Analysis Resources</h1>
        <p className={styles.description}>
        Code notebooks and tutorials for analysis and research applications  
        </p>

        <Gutter em={3} />

        <div className="row">
        <div className="col-xs-12 col-md-8 col-lg-12">
        </div>

        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Notebooks and Sample Code </h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <h3><a href="https://geodacenter.github.io/opioid-environment-toolkit/index.html">Opioid Environment Toolkit</a></h3>
              <p>
              The Opioid Environment Toolkit provides an introduction to GIS and spatial analysis for opioid environment applications. 
              This code toolkit supports researchers, analysts, and practitioners with learning open source spatial analytic and visualization services 
              in the R software environment. It covers topics such as geocoding MOUD resource locations, generating thematic maps, 
              linking community contextual data, and conducting a nearest distance analysis by calculating straight line/Euclidean distance metrics by zip codes. 
            </p>
            <h3><a href="https://colab.research.google.com/drive/1KXdKgKnXiRlKOuiSDVaBzplr7nrKy64B?usp=sharing#scrollTo=WbFT_hJQvdMP">Calculating Advanced Spatial Access Metrics</a></h3>
            <p>
            This Python notebook provides an overview of how to calculate two spatial access metrics, travel time to the nearest resource 
            (i.e. MOUD provider location), and count of resources within a specific driving time range. Using this beginner-friendly script 
            available as a Google Colab notebook (no Jupyter required), calculate metrics for specific states, regions, or spatial scales 
            using pre-computed travel cost matrices. We provide <a href="https://uchicago.box.com/s/ae2mtsw7f5tb4rhciczufdxd0owc23as">pre-computed travel time matrices</a>
            via Open Source Routing Machine for driving, walking, and biking travel networks, for all US Census tracts and zip codes (ZCTA).
            </p>
            <h3><a href="https://access.readthedocs.io/en/latest/index.html">Spatial Access for PySALs</a></h3>
            <p>
            Spatial accessibility measures help identify potential spatial mismatches between the supply and demand of services. 
            Developed by CSDS researchers and colleagues, this PySAL (Python Spatial Analysis Library) package and accompanying notebooks 
            implements a new measure that simultaneously accounts for travel time and congestion at the destination: Rational Agent Access Model (RAAM). 
            This package also calculates five classic spatial access models within the same class as RAAM for easy comparison, including 
            Floating Catchment Areas (FCA), Two-Step FCAs, and Access Score.
            </p>
        </div>
            
          </div>
        </div>

      <Gutter em={2} />

      <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Workshops and Trainings</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
          <h3><a href= "https://www.jcoinctc.org/maarc-virtual-workshop-series-summer-2021/">Spatial Dimensions of Opioid Risk Environments: Virtual Workshops</a></h3>
            <p>
            This three-part workshop series is designed to help researchers, analysts, and practitioners develop stronger spatial 
            data analytic and visualization skills. Led by the Healthy Regions/CSDS MAARC team, these workshops introduce basic spatial 
            analytic functionalities using open source tools, mainly in R and GeoDa, using applied examples. The workshops were 
            originally offered in Summer 2021 to the JCOIN and MAARC networks. The complete recordings are available below. 
            </p>
            <h4> Workshop 1: Introduction to Spatial Analysis for Opioid Risk Environments <a href="https://www.youtube.com/watch?v=8JLm_sF7gaA&t=2940s">[Recording]</a></h4>
            <p>
              This workshop introduces participants to the Opioid Environment Policy Scan (OEPS), key concepts in spatial data analysis, and how to generate simple maps using the free spatial software GeoDa.
            </p>
            <h4> Workshop 2: Geocoding and Linking Community Data <a href="https://www.youtube.com/watch?v=dHfQAhXXwh0&t=14s">[Recording]</a></h4>
            <p>
            This workshop introduces open source methods for geocoding Medication for Opioid Use Disorder (MOUD) resource locations 
            and other address data, integrating community characteristics data using geographic identifiers, and generating maps for exploratory analysis. 
            </p>
            <h4> Workshop 3: Developing Custom Spatial Access Metrics <a href="https://www.youtube.com/watch?v=SF5UumM1INk">[Recording]</a></h4>
            <p>
            This workshop instructs how to conduct a nearest resource analysis for MOUD resources at the community level, 
            calculate minimum distance access metrics, and generate maps overlaying resource locations and access metrics for further analysis.
            </p>
          
          </div>
        </div>

        <Gutter em={2} />

<div className="row">
    <div className="col-xs-12 col-md-4 col-lg-3">
      <h2> Talks </h2>
    </div>
    <div className="col-xs-12 col-md-8 col-lg-9">
      <h3> Opioid Environment Policy Scan: Open data for analyzing and visualizing the opioid risk environment </h3>
      <p>
      This talk was presented at the American Association of Geographers (AAG) Annual Conference in February 2022 by Susan Paykin. 
      It contextualizes the risk environment framework and outlines the data and structure of the OEPS. 
      Slides are available on <a href="https://github.com/spaykin/aag2022">GitHub</a>. 
      </p>
    
    </div>
  </div>

  <Gutter em={2} />


      </main>
      <Footer />
    </div>
  );
}
