import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

// const diagram = [
//   {
//     name:'oeps-diagram',
//     photo: 'oeps-diagram.png',
//   }
// ]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OEPS Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          media="print"
          onLoad="this.media='all'"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          />
        </noscript>
      </Head>
      <MainNav />
      <main className={styles.main}>
        <div className="row">
          <div className="col-xs-12 col-md-5 col-lg-4">
            <img src="images/oeps_diagram_mk2.png" className={styles.titleDiagram} />
            <Gutter em={3} />
          </div>
          <div className="col-xs-12 col-md-7 col-lg-8">
          <h1 className={styles.title}>
            Opioid Environment Policy Scan
          </h1>
          <p className={styles.description}>
          An open data warehouse exploring the multi-dimensional risk environment, from neighborhoods to states,
          impacting opioid use and health outcomes across the United States.
          </p>
          </div>
        </div>

        <Gutter em={2} />
        <div className="row rules">
          <div className="col-xs-12 col-md-4 col-lg-4">
            <img src="images/data.svg" alt="Data Documentation and download." className={styles.threeUpIcon} />
            <h1 className={styles.subhead}>Data</h1>
            <p>
              Access data by theme or spatial scale and explore our methdology. 
            </p>
            <p>
            <a
                className={styles.docsLink}
                href="/download "
              >
                Download &gt;
                </a>
            </p>
            <p>
            <a
                className={styles.docsLink}
                href="/docs "
              >
              Documentation &gt;
              </a> 
              </p>
              <p>
            <a
                className={styles.docsLink}
                href="/methods "
              >
              Methodology &gt;  
              </a> 
              </p>
              
          </div>

          <div className="col-xs-12 col-md-4 col-lg-4 rules-on">
            <img src="images/map.svg" alt="Map and explore data." className={styles.threeUpIcon} />
            <h1 className={styles.subhead}>Map</h1>
            <p>
            Visualize data with our interactive web map. 
            </p>
            <p>
            <a className={styles.docsLink} href="/map" > Start Mapping &gt;</a>
            </p>
          </div>

          <div className="col-xs-12 col-md-4 col-lg-4">
            <img src="images/insights.svg" alt="Data findings and further information." className={styles.threeUpIcon} />
            <h1 className={styles.subhead}>Insights</h1>
            <p>
              Learn about the OEPS, code resources, and research insights . 
            </p>
            <p>
            <a className={styles.docsLink} href="/about ">About &gt;</a> 
            </p>
            <p>
            <a className={styles.docsLink} href="/codeResources ">Code Resources &gt;</a> 
            </p>
            <p>
            <a className={styles.docsLink} href="/insights">Insights &gt;</a>
            </p>
              <p></p>
          </div>
        </div>
        <Gutter em={2} />
        <div className="row rules center-xs">
          <div className="col-xs-12">
            <h1>What is the OEPS?</h1>
          </div>
          <div className="col-xs-12 col-md-12 col-lg-10">
            <p>
            The Opioid Environment Policy Scan (OEPS) is an open-source data warehouse focused on the 
            multi-dimensional risk environment impacting opioid use and health outcomes across the United States. 
            </p>
            <p>
            The OEPS provides access to data at multiple spatial scales, from U.S. states down to Census tracts. It is designed 
            to support research seeking to study environments impacting and impacted by opioid use and opioid use disorder (OUD), 
            inform public policy, and reduce harm in communities nationwide. 
            </p>
            <p>
              The OEPS Explorer makes it quick and easy to explore, visualize, and download data. Read more <a href="/about">about the project</a>,  
              our <a href="/methods"> methodology</a>, and our <a href="/standards">data standards</a>. 
            </p>
            <p>
            The OEPS is led by the <a href="https://voices.uchicago.edu/herop/">Healthy Regions and Policies Lab</a>, based at the
            Center for Spatial Data Science at University of Chicago. It was developed for the <a href="https://heal.nih.gov/research/research-to-practice/jcoin">Justice Community Opioid Innovation Network (JCOIN)</a>, 
            an NIH HEAL Initiative, as part of the Methodology and Advanced Analytics Resource Center.
            </p>
          </div>
        </div>

        
      </main>
      <Footer />
    </div>
  );
}
