import Head from "next/head";
import styles from "../styles/About.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Insights :: OEPS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          media="print"
          onLoad="this.media='all'"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          />
        </noscript>
      </Head>
      <MainNav />
      <main className={styles.main}>
        <h1 className={styles.title}>Insights</h1>
        <p className={styles.description}>
        Research, data tools, and extensions of OEPS data. 
        </p>

        <Gutter em={3} />

        <div className="row">
        <div className="col-xs-12 col-md-8 col-lg-12">
        <p>
        Understanding the drivers and impacts of opioid use disorder (OUD) necessitates a nuanced, place-based consideration of communities and 
        varying dimensions of risk. We work on <a href="https://voices.uchicago.edu/herop/research/opioid-spatial/">multiple projects</a> that bring a holistic perspective to OUD social and spatial epidemiology, 
        building on a “risk environment” conceptual model with a social determinants of health sensibility. 
        </p>
        </div>

        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Research Articles</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
            Kolak, M.A., Chen, Y.T., Joyce, S., Ellis, K., Defever, K., McLuckie, C., Friedman, S. and Pho, M.T., 2020. 
            Rural risk environments, opioid-related overdose, and infectious diseases: A multidimensional, spatial perspective. 
            International Journal of Drug Policy.  
            <a href= "https://www.sciencedirect.com/science/article/abs/pii/S0955395920300682?via%3Dihub"> https://doi.org/10.1016/j.drugpo.2020.102727</a>
            </p>
            <p>
            Halpern, D., Lin, Q., Wang, R., Yang, S., Goldstein, S., and Kolak, M. (forthcoming). 
            Dimensions of uncertainty: A spatialtemporal review of five COVID-19 datasets. Cartography and Geographic Information Science. 
            https://doi.org/10.1080/15230406.2021.1975311
            </p>
        </div>
            
          </div>
        </div>

      <Gutter em={2} />

      <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Tools & Tutorials</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
          <h3> Opioid Environment Toolkit </h3>
            <p>
            The <a href="https://geodacenter.github.io/opioid-environment-toolkit/index.html">Opioid Environment Toolkit</a> provides an introduction to GIS and spatial analysis in R for opioid environment 
            applications that will allow researchers, analysts, and practitioners to support their communities with better 
            data analytics and visualization services. Chapters include Introduction to Spatial Data, Geocoding Resource Locations, 
            Thematic Mapping, and Nearest Resource Analysis. 
            </p>
            <h3> US COVID Atlas </h3>
            <p>
            The <a href="www.uscovidatlas.org">US COVID Atlas</a> is a near real-time, interactive data visualization platform and archive. The Atlas works to understand, 
            represent, and share stories of the often unequal impact of the COVID-19 pandemic in the United States, from January 2020 through today. 
            Data includes daily and weekly case counts, vaccination rates, and community health contexts. 
            Read more and explore at <a href="www.uscovidatlas.org">USCovidAtlas.org</a>. 
            </p>
          
          </div>
        </div>

        <Gutter em={2} />

<div className="row">
    <div className="col-xs-12 col-md-4 col-lg-3">
      <h2> Ongoing Research</h2>
    </div>
    <div className="col-xs-12 col-md-8 col-lg-9">
      <p>
      <b> Study (021): Spatially Extended Treatment Effect Analysis of Access to MOUD Resources and Changing Policies </b> | PI: Marynia Kolak
      </p>
      <p>
      The Healthy Regions & Policies Lab is developing a geospatial model to decompose and quantify the impact of access to MOUD and related services into different policy scenarios to inform future policy-making. This project will measure how local policies affect the impact of access to medication and service resources on opioid-related health outcomes, and build a risk environment warehouse to index all policy variables, both by spatial scale (census, tract, zip code, and county) and time (year).
      </p>
      <p>
      <b>Study (020): Finding an Optimal Distance of Success: Measuring Access to Critical Resources in Opioid Use Disorder Justice Settings</b> | PI: Marynia Kolak
      </p>
      <p>
      Accessing evidence-based medications and other critical resources for opioid use disorder (MOUD) is critical to saving lives and healing communities, 
      yet little is known on how access to these resources is best measured. The University of Chicago is conducting a geospatial modeling study 
      to measure optimal distance and access (e.g., availability, affordability, and acceptability) to MOUD and relevant resources to identify a 
      threshold of success that contributes to health outcomes. The study uses spatial analysis data and mapping software to identify what critical 
      resources are needed at a community level to support individuals with opioid use disorder (OUD).
      </p>
      <p>
      <b>Study (019): Measuring Social and Spatial Inequities in Access to Opioid Use Disorder Treatment for Reducing HIV and HCV Transmissions </b> | PIs: Marynia Kolak and Jonathan Ozik, Argonne National Lab
      </p>
      <p>
      Access to treatment and medication for opioid use disorder (MOUD) is essential for reducing HIV and HCV transmissions. 
      However, the spatial distribution of the resources for treatment and medication is a result of various social factors, which can include potential inequities.
      To demonstrate the utility of a spatial perspective in evaluating access to MOUD resources, 
      The University of Chicago and Argonne National Laboratory will use a simulation approach to evaluate how treatment and intervention locations 
      affect HIV and HCV transmissions. This study will also evaluate interventions using scenarios of varying levels of spatial inequity in HepCEP, 
      a validated agent-based model (ABM) for Hepatitis C Elimination in Persons Who Inject Drugs (PWID). Outcomes from this study may 
      provide insight into the complex factors that drive MOUD treatment heterogeneity within communities using more spatialized approaches for evaluation of efficacy.
      </p>
    
    </div>
  </div>

  <Gutter em={2} />

<div className="row">
    <div className="col-xs-12 col-md-4 col-lg-3">
      <h2> Partner Research</h2>
    </div>
    <div className="col-xs-12 col-md-8 col-lg-9">
      <p>
      We partner with numerous researchers and organizations working to address opioid risk environments. Below are a few active collaborations.
      If you are interested in collaborating or using OEPS data in your research,
      <a href="mailto:spaykin@uchicago,edu, mkolak@uchicago.edu"> let us know</a>.
      </p>
      <p>
        <b> Yale University </b>
        </p>
        <p>
        Research Article (in progress): Paul J. Jourdrey, Marynia Kolak, Qinyun Lin, Susan Paykin, Vidal Aguiano, Emily A. Wang. 
        Community social vulnerability and access to medications for opioid use disorder within the continental US: A cross-sectional study. 
        In progress, 2021. 
        </p>
        <p>
        <b> New York State Psychiatric Institute/Columbia University </b>
          </p>
          <p>
            Study (in progress): Facilitating Opioid Care Connections through System Level Strategies to Improve Use of Medications and 
            Linkages to Care Drug Courts across New York 
            </p>
            <p>
            <b> Chestnut Health Systems </b>
              </p>
              <p>
                Study (in progress): National Jail Survey: Interface between Criminal Justice and the Opioid Crisis
      </p>
      <p>
        <b> University of Chicago </b>
        </p>
        <p>
      Research Article (under review): Schneider, J., Taylor, B., Hotton, A., Lamuda, P., Ozik, J., Lin, Q., Flanagan, E., Pho, M., Kolak, 
      M., Brewer, R., Bather, J., and Pollak, H. (Under review). National variability in Americans’ COVID-19 
      protective behaviors: Implications for vaccine roll-out. 
      </p>
    
    </div>
  </div>






      </main>
      <Footer />
    </div>
  );
}
