import Head from "next/head";
import styles from "../styles/About.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Methods :: OEPS Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          media="print"
          onLoad="this.media='all'"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
          />
        </noscript>
      
        </Head>
      <MainNav />
      <main className={styles.main}>
        <h1 className={styles.title}>Methodology</h1>
        
      <Gutter em={5} />

        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Risk Environment Framework</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
                Organization and data selection for the OEPS is guided by a risk environment framework (<a href= "https://www.sciencedirect.com/science/article/pii/S0955395902000075">Rhodes 2002</a>). 
                The “risk environment” as a framework for understanding and reducing drug-related harms emphasizes the broader contextual domains 
                in which opioid use occurs. 
            </p>
            <p>
                Our approach is further rooted in the socioecological model of substance use, 
                which includes multiple levels of the physical and social environments that interact and overlap to impact health. 
                We apply this socio-ecological model of health and use it to further build on previous research on risk environments 
                (Cooper et al 2016, Ciccarone 2017). 
            </p>
            <p>
                Data and research models must reflect this transdisciplinary and multi-level approach. The risk environment framework 
                shifts the focus of drug-related harm research away from individuals, 
                and toward environmental factors driving or enabling trends at the community level. 
                We see this approach encouraging greater understanding of the spatial and community contexts in which opioid use harm occurs. 
            </p>
          </div>
        </div>

      <Gutter em={2} />

      <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Multiple Spatial Scales</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
                Most datasets are available at multiple spatial scales, including Census tract, 
                ZIP Code or ZIP Code Tract Area (ZCTA), county, and state. You can filter and explore available datasets by spatial scale <a href="/docs">here</a>.
            </p>
        
          </div>
        </div>

        <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Data Themes</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Data included in the OEPS is grouped thematically for ease of exploration, indices development, and model integration. 
        Data is stratfied across six themes: 
        </p>
        <p>
        
        <li> <b> Policy:</b> State, county, and local policies that may influence access to treatment and/or criminal justice </li>
        <li> <b>Health:</b> Health outcomes, physicians, access to MOUDs and healthcare resources, and more </li>
        <li> <b>Demographic:</b> Age, gender, race/ethnicity, social vulnerability, social determinants of health, and more</li>
        <li> <b>Economic:</b> Employment trends, income, poverty, foreclosure rates, and more</li>
        <li> <b>Physical Environment:</b> Housing, urban-suburban-rural classification, community overlays</li>
        <li> <b>COVID-19:</b> Essential workers, daily infection rates and confirmed cases through March 2020.*</li>
        
        <p> <i>*For complete case rate, mortality, and additional COVID-19 data, please visit the <a href="www.USCovidAtlas.org">US COVID Atlas</a> -- 
        a free and open source pandemic data archive and visualization tool, also led by the Healthy Regions and Policies Lab.</i>  </p>
        
        <p> The OEPS also includes <b>geography boundary</b> shapefiles from the US Census Bureau’s TIGER/Line (2018) for Census tracts, ZCTAs, counties, and states.</p>

        </p>
  
    </div>
  </div>

  <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Data Standards</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Please see the <a href= "/standards">Data Standards</a> page for more on our file naming conventions, geographic identifiers, data formatting, and guidelines for contributors. 
        </p>
  
    </div>
  </div>

  <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Documentation</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Please refer to the <a href= "/docs">Metadata Docs</a> or the complete <a href= "https://docs.google.com/document/d/18NPWpuUfFTrKll9_ERHzVDmpNCETTzwjJt_FsIvmSrc/edit?usp=sharing">Data Documentation </a> 
         for more information about individual datasets and variables.
        </p>
  
    </div>
  </div>
        

      </main>
      <Footer />
    </div>
  );
}
