# This is a basic workflow to help you get started with Actions

name: Data Cleaning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [main, qaqc-applied]
  #pull_request:
  #  branches: [main, qaqc-applied]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r qaqc/requirements.txt
      - name: qaqc data
        run: python qaqc/clean.py
      - name: Commit
        uses: zwaldowski/git-commit-action@v1
        with:
          # Commit message
          commit_message: QAQC Data cleaning